name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Copy files to docs
      run: |
        mkdir -p docs
        cp login.html docs/index.html
        cp login-style.css docs/
        cp login-script.js docs/
        cp index.html docs/dashboard.html
        cp style.css docs/
        cp script.js docs/
        cp README.md docs/
        echo "Preventivi Pro - Professional Quote Generator" > docs/CNAME
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4